[mypy]
# This is a new clean codebase — be tighter than the older rubintv_production
# config. The aim is to keep mypy-coverage high (see the README) and refuse
# untyped defs in the package itself.
ignore_missing_imports = False
check_untyped_defs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
warn_unused_ignores = True
warn_redundant_casts = True
enable_error_code = possibly-undefined

files = ra_log_explorer/
explicit_package_bases = True
namespace_packages = True
